### ISSUE TITLE
Feil syntax på oppgaven McB-14

### ISSUE THREAD

**Issue by fuzzbin** [fagstoff/IT1#12]
Kan du sjekke om det er en syntaxfeil i oppgaven:

Du bruker mysql_connect_errno() , men jeg sliter med denne. Skal dette være mysql_errno()?

http://us2.php.net/manual/en/function.mysql-errno.php

**Comment by bitjungle** [comment]
Vil ikke bruke mysql_errno(), den er "deprecated". Jeg bruker http://us2.php.net/manual/en/function.mysqli-connect.php, den skal funke fint den. Hva slags problem har du? Feilmelding?

**Comment by bitjungle** [comment]
Jeg testet nå, ingen problemer her. Er du sikker på at du har fylt inn $db_host, $db_navn, $db_bruker og $db_pass riktig? Har du oppretta tabellen 'Bestillinger'?

**Comment by fuzzbin** [comment]
Det var en (flink) elev som meldte fra. Jeg har ikke fått testet selv ennå. Jeg så bare på koden, og googlet litt. Skal teste selv litt senere i kveld. Regner med at det er riktig som du sier. Vi kan merke denne som solved.

**Comment by fuzzbin** [comment]
Ok, testet selv nå. Koden er grei. :-)
