### ISSUE TITLE
Oppdatere skjermbilder

### ISSUE THREAD

**Issue by bitjungle** [fagstoff/IT1#14]
Oppdatere skjermbilder på noen (mange?) mcbergbys-oppgaver sånn at url-en i adressefeltet til nettleseren stemmer overens med det som er gitt i oppgaveteksten.

**Comment by fuzzbin** [comment]
Har begynt, men jeg har ikke photoshop. Jeg er heller ikke så god på grafisk design. Kan du lage en ramme som du syntes er fin, så kan jeg følge malen din på resten av bildene?

**Comment by bitjungle** [comment]
Lukker sak som er fikset for lenge siden.
