### ISSUE TITLE
Samsvar mellom løsningsforslag og oppgaver.

### ISSUE THREAD

**Issue by fuzzbin** [fagstoff/IT1#16]
Jeg oppdaget at løsningsforslaget til McB15 ikke stemmer med oppgaveteksten. I løsningsforslaget blir det generert meny ved hjelp av php. Kan du sjekke og bekrefte @bitjungle ?

**Comment by bitjungle** [comment]
Skal se på det i dag.

**Comment by bitjungle** [comment]
Fikset oppgave 15 og 16.
