### ISSUE TITLE
Alternativ til w3schools

### ISSUE THREAD

**Issue by bitjungle** [fagstoff/IT1#2]
Lenker til materialet fra w3schools i HMTL Multimedia i fila https://github.com/bitjungle/IT1/tree/master/Fagtekster/Nettsteder%20og%20multimedier. Dessverre er w3schools "all rights reserved". Finnes det annet materiale som er minst like godt egnet i denne sammenhengen, og som har en mer liberal lisens? Helst på norsk!

**Comment by fuzzbin** [comment]
Les her: Det kan hende denne ressursen går innunder det som kalles "fair use" Man kan jo spørre Refnes data om det?

Se kulepunkt 2:
Favorable Use:
Copying examples and code snippets for non-profit teaching and research.
**Copying small quantities, appropriate for classroom teaching.**

http://www.w3schools.com/about/about_copyright.asp

**Comment by bitjungle** [comment]
Bra nok for meg, lukker sak.
