### ISSUE TITLE
Legg til to dokumentarer Cambridge Analytica

### ISSUE THREAD

**Issue by mimmelim** [fagstoff/IT1#21]
https://tv.nrk.no/program/KOID22003518/cambridge-analytica-en-trussel-mot-demokratiet

https://tv.nrk.no/serie/silicon-valley-ute-av-kontrolle/KOID23004817/27-03-2018

**Comment by bitjungle** [comment]
Har lagt dem inn her (med engelske titler, sånn at det går an å finne dem igjen når de forsvinner fra NRK): https://github.com/fagstoff/IT1/blob/master/Oppgaver/Digital%20samtid/To%20av%20syv.md
