### ISSUE TITLE
Opphavsrettsklarert tekst og bilde

### ISSUE THREAD

**Issue by bitjungle** [fagstoff/IT1#3]
Se https://github.com/bitjungle/IT1/blob/master/Oppgaver/Nettsteder%20og%20multimedier/Ostekake.md. Er teksten opphavrettsklarert? Hva er kilden? Hva med bildet? Bør vi legge et bilde i Bilder-mappa som elevene kan bruke?

**Comment by fuzzbin** [comment]
Ser at jeg må gå igjennom flere av oppgavene for å sjekke bildene. De fleste er klipp og lim fra Google bildesøk. Skal kvalitetssikre disse. Noen av oppgavene er noen år gamle. Burde ha sjekket bedre før publisering. Når det gjelder ostekakeoppskriften så skal jeg sjekke kilden.

**Comment by fuzzbin** [comment]
Har begynt å kvalitetssikre oppgavene. Ser det greit ut?

https://docs.google.com/document/d/1HDCm7vnwHKQVH4UEGdRqowHI_N6qFWhNGVg4uWpzKTo/edit
Jobber meg gjennom resten av oppgavene fortløpende.

**Comment by fuzzbin** [comment]
Har oppdatert ostekake- og timeplanoppgaven. La bilder i bildemappa og oppdaterte oppgavetkst. Når det gjelder teksten i ostekakeoppgaven så mener jeg det er en standard oppskrift. Husker ikke hvor den kommer fra. Kan godt omformulere den om ønskelig. Mulig den kommer fra et forum eller noe slikt. Den er ikke generert av en oppskriftsside.

**Comment by bitjungle** [comment]
Ser bra ut, lukker sak.
