### ISSUE TITLE
IT2-logo

### ISSUE THREAD

**Issue by fuzzbin** [fagstoff/IT1#4]
Kan du lage en IT2-versjon av IT1-logoen?

**Comment by bitjungle** [comment]
Jeg har brukt denne fonten: http://www.fontsquirrel.com/fonts/montserrat
Prøv selv, og se om du synes det blir ok med IT2.

**Comment by bitjungle** [comment]
Jeg har testen nå, IT2 fungerer ikke like godt med Montserrat. Foreslår at vi finner en ny font som gir et tøft resultat for begge fag. Jeg tester http://www.fontsquirrel.com/fonts/Akashi nå, synes det ser lovende ut.

**Comment by fuzzbin** [comment]
Enig!
