### ISSUE TITLE
Bildet i McBergbys 3b vises ikke

### ISSUE THREAD

**Issue by fuzzbin** [fagstoff/IT1#7]
Jeg ser at oppgaven ikke er merket ferdig, men har du bildet klart?

**Comment by bitjungle** [comment]
Nei, ikke noe bilde her. Har ikke gjort noe arbeid med denne oppgaven ennå. Tar gjerne imot hjelp. Har tenkt at det skal være en oppgave som erstatter Timeplanen 1.0 og 2.0 (og kanskje 3.0).

**Comment by fuzzbin** [comment]
Ok, skal se hva jeg kan få gjort. Har noen elever som har begynt å snuse på oppgavene fremover, så det var slik jeg ble oppmerksom. :-)

**Comment by bitjungle** [comment]
Jeg rekker dessverre ikke å gjøre noe mer med den nå, men om vi ikke har noe klart er Timeplan-oppgavene fine. Dumt at det bryter med McBegbys-oppgaverekka, men ellers helt ok.

**Comment by fuzzbin** [comment]
<img width="661" alt="skjermbilde 2016-09-14 kl 22 06 51" src="https://cloud.githubusercontent.com/assets/4933606/18528868/07d3f678-7acb-11e6-8057-4fc6c9c9379d.png">

Ganske enkel tabell med litt CSS. Hva tenker du?

**Comment by bitjungle** [comment]
Brukte utkastet fra fuzzbin, ferdigstilte oppgave 3b.
