### ISSUE TITLE
McBergbys del6

### ISSUE THREAD

**Issue by fuzzbin** [fagstoff/IT1#9]
Det er noe galt med videofilene. Det var en elev som gjorde meg oppmerksom på at hun slet med å spille av filmene som ble lastet ned. Jeg testet og fikk det heller ikke til. Lastet ned så to filmer direkte fra BigBuckBunny-nettsiden og testet med disse. Det fungerte. Kan du sjekke?

**Comment by bitjungle** [comment]
Videoen funker, men det er noe muffens med download-funksjonen i github. Har satt lenka i oppgava direkte til videofila nå, så kan elever lagre "siden" i nettleseren.
